### ISSUE TITLE
rtk creates a giant window on macOS

### ISSUE THREAD

**Issue by StephanRoemer** [jtackaberry/rtk#8]
MacBook Air M1
macOS 12.1
REAPER 6.41 RC1
SWS 2.12.1.3
JS API 1.220

When using the hello world example code, I get a giant script window in macOS:

![VNFfVpX](https://user-images.githubusercontent.com/34496643/151860953-833c4bce-b32e-468f-b11f-0742d8bc3e08.png)

**Comment by StephanRoemer** [comment]
Indeed, Reaticulate doesn't work here, either.

**Comment by jtackaberry** [comment]
You know, I've been waffling about picking up a MacBook Air M1 for some time, mainly so I had better test coverage for Reaticulate.  (It would be my first Apple product in my life.)  This might tip me over to hasty impulse buy territory.

A few things meanwhile:
1. Can you upgrade to the latest stable REAPER?
2. Is the behavior different if you remove JS extension?
3. Likewise, if you then also remove SWS, in addition to JS?

Thanks!

**Comment by StephanRoemer** [comment]
Updated to the latest stable release, didn't do anything, though.
BUT, removing JS API did the trick!

EDIT: and yes, the MacBook Air M1 is a really nice device!

**Comment by jtackaberry** [comment]
Ok, this does narrow it down, but not by much: rtk.Window's use of the JS API is a maze of twisty little passages.

Perhaps I'll drop by the local Apple store tonight and see if they have something in stock that won't make my wallet weep. :)

**Comment by StephanRoemer** [comment]
This is really strange, hmm!

Yes, I can see you clicking the purchase button 😅

**Comment by jtackaberry** [comment]
Ok, so, yeah, I can reproduce it.  What a mess.  My OS X VM and high-DPI Windows certainly was not sufficient to validate things.  REAPER on OS X retina displays simply works differently than everything else.

There are legit rtk bugs here that I need to fix, but one thing I'm running into right now is what seems to be a bug with both SWS and JS API.

Are you able to try running this code and see what the output is?

```lua
    local l, t, r, b = reaper.JS_Window_GetViewportFromRect(0, 0, 1, 1, false)
    local sws_w, sws_h = r - l, math.abs(b - t)
    l, t, r, b = reaper.BR_Win32_GetMonitorRectFromRect(false, 0, 0, 1, 1)
    local js_w, js_h = r - l, math.abs(b - t)
    reaper.ShowConsoleMsg(string.format('SWS: %sx%s\nJS: %sx%s\n', sws_w, sws_h, js_w, js_h))
```

And then from the terminal, run:

```bash
system_profiler SPDisplaysDataType | awk '/Resolution/{print $2, $3, $4}'
```

On my shiny new Macbook Air M1, the ReaScript outputs 1440x900 for both SWS and JS.  Meanwhile the official display resolution, as confirmed by `system_profiler` is 2560x1600.

Do you see the same thing?

**Comment by jtackaberry** [comment]
Actually, scratch that. It's not a bug.  OS X actually presents as a 1440x900 display. 

Well, the good news is I have a proper device to test this now.  It'll take me a couple days to hash this out I think.  rtk's goal is to make all this work exactly the same on all platforms, but it means a lot of juggling under the hood.

**Comment by StephanRoemer** [comment]
I didn't expect you to get the MacBook Air THAT quickly, haha!
Crossing my fingers that you get it working without a lot of effort!

**Comment by jtackaberry** [comment]
> I didn't expect you to get the MacBook Air THAT quickly, haha!

Like I said, impulse buy. :)  The exercise has been good for me in that it's made me really appreciate Linux and Windows.  Windows in particular pisses me off, and I confess I always had a sense of FOMO with OSX.  The past day has pretty much eliminated all concerns I had that the Mac experience is superior -- it's got its fair share of weird, inexplicable, and broken shit.  The most recent faceplam is the realization that you can't prevent the thing from going to sleep when you close the lid on battery, at least not without a third party application.  (And my experience trying to install said third party application merits a rant by itself.)

Yep, this MacBook is going to be relegated to testing.  I really don't see myself using it for anything serious.  It is undoubtedly a sexy device though.

>  Crossing my fingers that you get it working without a lot of effort!

You and me both!

**Comment by StephanRoemer** [comment]
Yikes, didn't expect you have such a bad experience with it, LOL! 🙈 
I use it mainly for web, mail and coding. REAPER is installed but I don't use it for making music 😛

**Comment by jtackaberry** [comment]
I'm making progress, but it's all getting very complex.  REAPER does this annoying thing where it presents `gfx.w` and `gfx.h` as doubled for retina displays, which sounds logical until you realize that if you call `gfx.init()` with the previous values of `gfx.w/h` to restore the window size from the last session, it doubles each time.

Then after compensating for that, you face the next problem which is that while the dimensions are doubled, the display resolution bears no reflection of reality because OS X does display scaling (which is configurable in System preferences). For example, you call `gfx.init()` with a width of 800, `gfx.w` afterward reports 1600, and `JS_Window_GetViewportFromRect()` tells you the display width is 1440 -- i.e. less than the window width, even though the window is *actually* only about 60% of the screen width.

Worse, while the dimensions are pixel-exact, the x/y coordinates are scaled.  So if you take the window's x position, add the window's width, do you think you're at the right edge of the window?  No, you're in Timbuktu.  I have no idea how developers cope with this insanity.  Quantum physics makes more sense.  So I really no clue to do something straightforward like center a window.  Unless I can figure that out, I'll need to disable the [rtk.Window:open() alignment arguments](https://reapertoolkit.dev/class/rtk.Window.html#rtk.Window.open) on Mac.  (Edit: ok, think I figured that out.)

rtk's API normalizes the window's `y` coordinate so it behaves the same on all platforms (on Mac, y=0 means bottom of the screen, on all other platforms y=0 is top of screen, so rtk tries to make this consistent), which, when combined with all the above weirdness, it ends up being a brittle mindfuck.  rtk's goal is to abstract away all this nonsense into a consistent API that behaves the same on all platforms and configurations, and when accounting for Mac with retina displays that's no small feat!

Anyway, working through it.  Hope to have a dev build out on Friday or Saturday for you to kick around.  Meanwhile, if you want to do some coding, you can just force-disable rtk's use of the JS API:

```lua
rtk.has_js_reascript_api = false
```

**Comment by StephanRoemer** [comment]
Hey Jason, goodness, that really sounds like a shit show.
However, I knew about the y=0 thingy. I think it's the same for Windows and Linux but different for macOS.
Damn, I should have told you! There are also a couple of threads about it on the forums. But I guess you already figured it out by now. Well done, Jedi!

**Comment by jtackaberry** [comment]
Oh the y coordinate differences isn't a new discovery. rtk already abstracts these differences away and normalizes the y coord on all platforms (and this is documented). It's just that this feature is really complicated by all the other things I mentioned. And yeah, Mac is the odd man out: Linux and Windows are consistent.

**Comment by StephanRoemer** [comment]
Ah sorry, my bad then! Would have surprised me if you hadn’t taken care of that already!

**Comment by jtackaberry** [comment]
@StephanRoemer I _finally_ have something to show for my investment. :)

Attached is a dev build. If you have the time, I'd be grateful if you could test it out on your system.

[rtk.zip](https://github.com/jtackaberry/rtk/files/8057533/rtk.zip)

I ended up abandoning the attempt to normalize [rtk.Window.y](https://reapertoolkit.dev/class/rtk.Window.html#rtk.Window.y) on all platforms, and gave into the pressure to have it work differently on Mac.  The only way I am able to normalize the y coordinate is by discovering the screen resolution, which only works when either SWS or JS is available.  But one of rtk's design goals is that core functionality works without these extensions, so the whole thing was doomed from the start.

Currently the `halign` and `valign` options passed to [`rtk.Window:open()`](https://reapertoolkit.dev/class/rtk.Window.html#rtk.Window.open) doesn't work yet -- that needs a bit more head-scratching -- but everything else should be working. 🤞

**Comment by StephanRoemer** [comment]
Will test ASAP, thanks Jason!

**Comment by jtackaberry** [comment]
> Indeed, Reaticulate doesn't work here, either.

Don't suppose you could test out the latest Reaticulate prerelease via ReaPack on your M1 and let me know if it's looking better? https://reaticulate.com/prerelease.xml

Thanks!

**Comment by StephanRoemer** [comment]
Just tested it and IT WORKS! 🥳

**Comment by StephanRoemer** [comment]
And yes, rtk.lua also works, awesome!

**Comment by jtackaberry** [comment]
Thanks Stephan!  Will cut a proper release of both next. Appreciate the help.
